### ISSUE TITLE
Criar uma versão em inglês do README

### ISSUE THREAD

**Issue by augusto-herrmann** [turicas/covid19-br#100]
Ter uma versão em inglês do README ajudaria a dar mais visibilidade aos dados coletados pelo Brasil.io, que é a única fonte aberta diária de dados em nível de município sobre a Covid-19 no Brasil, a nível internacional.

Podemos tomar como exemplo [este repositório de dados sobre a Covid-19 na França](https://github.com/opencovid19-fr/data), que é uma iniciativa semelhante a esta para os dados de fontes oficiais francesas. No README, que está em francês, há no início um link para [a versão em inglês do mesmo texto](https://github.com/opencovid19-fr/data/blob/master/README.en.md).

**Comment by arielcavalcante** [comment]
WIP #112

**Comment by whaner** [comment]
Vou ajudar na tradução das páginas...

**Comment by endersonmaia** [comment]
@whaner concluímos a tradução do README aqui f927777
