### ISSUE TITLE
Inconsistência entre dados por município e dados agregados por estado

### ISSUE THREAD

**Issue by fndemarqui** [turicas/covid19-br#105]
Aparentemente há um problema na base de dados. A soma dos casos novos  confirmados quando consideramos os dados em nível de municípios é diferente da soma obtida quando os dados são agregados por estado (usando place_type=="state").

**Comment by endersonmaia** [comment]
https://github.com/turicas/covid19-br/blob/master/faq.md#as-contagens-estaduais-podem-ser-diferentes-das-municipais
