### ISSUE TITLE
Sem dados de MG

### ISSUE THREAD

**Issue by luizchiaradia** [turicas/covid19-br#107]
https://brasil.io/api/dataset/covid19/caso/data/?is_last=True&state=MG Os dados de MG não estão sendo exibidos.

**Comment by wcota** [comment]
RN também sumiu. https://brasil.io/covid19/RN/
"500

Oops! Aconteceu um problema com nosso servidor, não se preocupe que já fomos notificados e trabalharemos para corrigir. "

MG dá o mesmo erro https://brasil.io/covid19/MG/

**Comment by wcota** [comment]
Os dados voltaram! :)

**Comment by endersonmaia** [comment]
possível intermitência do sistema, vou fechar a issue
