### ISSUE TITLE
Painel COVID Registral. Óbitos por doenças respiratórias do registrocivil.org

### ISSUE THREAD

**Issue by avila** [turicas/covid19-br#118]
Há planos de incluir as informações adicionais do [Painel COVID Registral](https://transparencia.registrocivil.org.br/registral-covid) do portal da transparência do registro civil?  

Neste painel eles incluiram: 
-    Síndrome respiratória aguda grave (SRAG)
-    Pneumonia
-    Insuficiência respiratória
-    Septicemia (sepse/choque séptico)
-    Indeterminadas (causas mortes ligadas a doenças respiratórias, mas não conclusivas)
-    Demais óbitos (todos os outros tipos de óbitos que não estão listados a cima)

Com esses dados deve ser possivel calcular, de forma mais precisa, o excesso de mortes.

**Comment by turicas** [comment]
@endersonmaia obrigado! Não sabia que existia essa possibilidade. :)

**Comment by capyvara** [comment]
API:
```
# Pega as cidades
GET https://transparencia.registrocivil.org.br/api/covid-cities
total=filtro de mortes minimas
type=registral-covid
Array com { city_id, nome, uf, total }

# Pega os registros
GET https://transparencia.registrocivil.org.br/api/covid-covid-registral
start_date=YYYY-MM-DD
end_date=YYYY-MM-DD
state=Todos AC AL AM AP BA CE DF ES GO MA MG MS MT PA PB PE PI PR RJ RN RO RR RS SC SE SP TO
city_id=all ou alguma da lista acima # opcional
chart=chart1 chart2 chart3 # default chart1 agregado, chart2 por faixa etária homem, chart3 faixa etária mulher, não entendi pq tem chars diferentes de tem o parâmetro gender
gender=M F 
```

**Comment by capyvara** [comment]
Acho que da para fazer, todos os estados, por dia, o agregado e esquecer as faixas etárias por enquanto? senão vão ficar muitas colunas se não puder fazer um database relacional

**Comment by capyvara** [comment]
https://twitter.com/oatila/status/1256756480621117441

Pontos levantados:
- É importante granulação por cidade
- Dados em constante mudança, mesmo para +30 dias no passado

O que acham?
- Um scrap diário por estado
- Outro por semana epidemiológica para todas cidades com mais de 100 óbitos (~2500)
- Talvez fazer um diário por cidade para algumas especiais?

**Comment by capyvara** [comment]
Pode ter atraso de até 1 mês:
https://projetocomprova.com.br/wp-content/uploads/2020/05/null-9.png

**Comment by capyvara** [comment]
Proponho umas alterações para adicionar cidade, colocar local da morte e minimizar a quantidade de colunas.

| name | type | notes |
|----------------------------|------|---------------------------------|
| last_updated | date | Dia que foi coletado ? #102  |
| date | date |  |
| state | text |  |
| city | text |  |
| city_ibge_code | i | integer |
| epidemiological_year | integer |  |
| epidemiological_week | integer |  |
| place_type | text | hospital, home, streets, others |
| deaths_sars | integer |  |
| deaths_pneumonia | integer |  |
| deaths_respiratory_failure | integer |  |
| deaths_septicemia | integer |  |
| deaths_indeterminate | integer |  |
| deaths_others | integer |  |
| deaths_covid19 | integer |  |

**Comment by turicas** [comment]
Vou fechar essa issue dado que esses dados já estão na plataforma, sendo atualizados diariamente. Inclusive, temos dados até o fim do ano para 2019 (valeu, @capyvara!).

**Comment by leo-smi** [comment]
Teria como adicionar os dados por municípios no site?

**Comment by turicas** [comment]
Para facilitar, criei [a label "cartórios"](https://github.com/turicas/covid19-br/labels/cart%C3%B3rios), assim fica fácil agrupar todas as issues relacionadas aos dados coletados do Portal da Transparência do Registro Civil.
