### ISSUE TITLE
Nome da cidade embranco Estado MG.

### ISSUE THREAD

**Issue by murilobsd** [turicas/covid19-br#12]
Boa Tarde, o nome de uma cidade do estado de Minas Gerais se encontra embranco, como mostra a imagem abaixo.

**DATASET**: Covid-19
**Página** (Paginação): 3
**Navegador**: Firefox 74.0
**S.O.**: OpenBSD-6.6

![image](https://user-images.githubusercontent.com/3185376/77196265-bcfab200-6ac1-11ea-8728-9ee2e68134aa.png)

**Comment by turicas** [comment]
Tipo de local: state. É dado da UF e não do município.
