### ISSUE TITLE
ERRO- Dados cartórios COVIDdo dia 5/maio não estão atualizados

### ISSUE THREAD

**Issue by ramsev** [turicas/covid19-br#122]
Pessoal, apesar de o sistema dizer ter sido atualizado recentemente, as atualizações do dia 5 de maio não estão capturados.

obrigado

**Comment by endersonmaia** [comment]
olá @ramsev, envia mais detalhes por favor.

a qual endereço (URL) e/ou arquivo vc está se referindo ?

se possível, enviar exemplos e capturas de tela, isso ajuda a gente a identificar o problema.

**Comment by ramsev** [comment]
aqui vai o link, filtrei o estdo do RJ só para ficar mais fácil de ver a
data:
https://brasil.io/dataset/covid19/obito_cartorio/?search=&date=&state=RJ&epidemiological_week_2019=&epidemiological_week_2020=

veja que diz que foi atualizado dia 5 as 25h, mas o dado mais recente é do
dia 4. Em tese poderia apenas ser que dados desses dias ainda não foram
registrados pelos cartórios, mas no site do CRC você já encontra
informacoes deles. Além disso, eu fiz uma extração no dia 4 de maio, e os
números estão praticamente iguais, sendo que no site dos cartórios é
possível ver que houve um aumento relevante de óbitos

Em qua., 6 de mai. de 2020 às 09:58, Enderson Tadeu S. Maia <
notifications@github.com> escreveu:

**Comment by ramsev** [comment]
Na verdade, embora no site de vocês apareça que a atualização foi as 23h do
dia 5, quando se baixa o dataset diz que a aultima atualização foi as 9:30:

[image: image.png]

Em qua., 6 de mai. de 2020 às 10:03, Ramiro Severo <ramiro.severo@gmail.com>
escreveu:

**Comment by endersonmaia** [comment]
@ramsev acontece que as atualizações são feitas várias vezes ao dia, de acordo com a liberação dos dados pela SES e coleta pelos voluntários, não é automático ainda

quando aos dados dos cartórios, é outra fonte de dados, que tem atualizações em periodicidade diferente


> Ess tabela contém dados de óbitos por suspeita/confirmação de covid19, pneumonia ou insuficiência respiratória registrados nos cartórios e disponíveis no Portal da Transparência do Registro Civil.
DADOS INCOMPLETOS: os cartórios podem demorar algumas semanas para consolidar os dados e, portanto, os dados dos 14 últimos dias (pelo menos) são incompletos e serão atualizados no futuro. Caso queira ter certeza de que está trabalhando com números finais (ou quase finais), utilize dados anteriores a 30 dias da data de atualização desse dataset.
Além de acessar os dados por essa interface você pode também baixar o dataset completo ou acessá-lo via API.

Leia : 

* https://github.com/turicas/covid19-br/blob/master/faq.md
* https://github.com/turicas/covid19-br/blob/master/api.md#óbitos-registrados-em-cartório

**Comment by ramsev** [comment]
eu entendo que são feita várias vezes ao dia, mas no site de vocês diz que a ultima atualização foi as 23h do dia 5. Isso teria capturado a atualização das 12am dos cartórios. Mas não está. Obrigado e parabéns pelo trabalho

**Comment by endersonmaia** [comment]
> Isso teria capturado a atualização das 12am dos cartórios.

leia o texto citado no meu comentário anterior sobre os dados dos cartórios
