### ISSUE TITLE
Dados do AM atrasados desde 24 de Maio - algo que eu possa ajudar?

### ISSUE THREAD

**Issue by jecogeo** [turicas/covid19-br#151]
Amigos, os dados do AM estão sem atualização desde domingo, 24 de Maio. Pelas issues que acompanhei aqui, parece que tem algo a ver com os boletins, correto? No entanto, os dados apresentados em http://saude.am.gov.br/painel/corona/ estão sendo atualizados. Se tiver algo que eu possa fazer para ajudar a atualizar os dados do AM, por favor, me digam que farei o possível (dentro das minhas limitações em programação).

**Comment by endersonmaia** [comment]
olá @jecogeo , dá uma lida no https://github.com/turicas/covid19-br/blob/master/CONTRIBUTING.md

vou fechar essa issue, já que não é o melhor canal para esta discussão
