### ISSUE TITLE
[Dúvida] A API do Covid-19 também consegue pegar dados de outros países?

### ISSUE THREAD

**Issue by ncesar** [turicas/covid19-br#164]
Ou apenas do BR?
Uma outra dúvida, como pegar os dados gerais apenas do Brasil(o somatório dos números de todos estados/cidades) invés de coletar tudo de uma vez?

**Comment by endersonmaia** [comment]
Nós só coletamos dados do Brasil, leia aqui : https://github.com/turicas/covid19-br/blob/master/faq.md

Sobre acesso à API, leia aqui : https://github.com/turicas/covid19-br/blob/master/api.md

**Comment by ncesar** [comment]
Desculpe comentar de novo mas mesmo lendo o `api.md` eu não achei onde fala sobre um request para pegar dados do Brasil apenas(sem retornar um .json com estados/cidades).
Ex:
```json
    {
      "country": "Brazil",
      "city_ibge_code": "null",
      "confirmed": 30000,
      "confirmed_per_100k_inhabitants": 4.98355,
      "date": "2020-03-26",
      "death_rate": null,
      "deaths": 30000,
      "estimated_population_2019": 2000066,
      "is_last": true,
      "place_type": "country"
    },
```

**Comment by endersonmaia** [comment]
@ncesar vc não achou pq não tem mesmo

vc pode abrir uma issue sugerindo a implementação ou mandar um PR implementando

lembrando que a API é implementada no projeto https://github.com/turicas/brasil.io
