### ISSUE TITLE
API deveria retornar dados totalizados para o Brasil

### ISSUE THREAD

**Issue by ncesar** [turicas/covid19-br#165]
Gostaria de saber se é possível receber um json dessa maneira(e com apenas o Brasil de objeto, sem outros extras): 
```json
    {
      "country": "Brazil",
      "city_ibge_code": "null",
      "confirmed": 30000,
      "confirmed_per_100k_inhabitants": 4.98355,
      "date": "2020-03-26",
      "death_rate": null,
      "deaths": 30000,
      "estimated_population_2019": 2000066,
      "is_last": true,
      "place_type": "country"
    },
```

Por exemplo: `https://brasil.io/api/dataset/covid19/caso/data?country=Brasil`

Não achei nada à respeito na [API](https://github.com/turicas/covid19-br/blob/master/api.md), apenas maneiras/exemplos que pegam informações de cidades/estados, nenhum que pegue apenas o somatório total do Brasil. Me desculpem se deixei passar e não achei..

**Comment by endersonmaia** [comment]
@turicas sugiro mover isso pro https://github.com/turicas/brasil.io como feature request

**Comment by ncesar** [comment]
Vou criar uma issue lá @endersonmaia , obrigado!
