### ISSUE TITLE
Adicionar ao clipping

### ISSUE THREAD

**Issue by turicas** [turicas/covid19-br#171]
Links dos últimos dias, que ainda não consegui organizar pra colocar no clipping.md - se alguém puder fazer será ótimo =)

https://apublica.org/2020/06/na-trincheira-contra-o-apagao-de-dados-da-pandemia/
https://bandnewsfmcuritiba.com/voluntarios-criam-plataforma-que-atualiza-casos-de-coronavirus-em-todas-as-regioes-brasileiras/
https://brazilian.report/coronavirus-brazil-live-blog/2020/06/07/brazilians-responds-to-government-tampering-with-covid-19-data/
https://cbn.globoradio.globo.com/media/audio/304208/iniciativas-utilizam-tecnologia-para-coletar-e-div.htm
https://covid19sc.github.io/
https://github.com/wendeldavid/covid-19-alexa-skill
https://infovis.sei.ba.gov.br/covid19/
https://mais.opovo.com.br/jornal/reportagem/2020/06/09/a-importancia-de-se-disponibilizar-dados-para-a-saude.html
https://mais.opovo.com.br/jornal/reportagem/2020/06/09/stf-manda-ministerio-da-saude-voltar-a-divulgar-dados-acumulados.html
https://saude.estadao.com.br/noticias/geral,governos-e-sociedade-fazem-contagem-paralela-de-casos,70003328908 (manchete - ver tweet no twitter.com/estadao pra linkar tweet da imagem )
https://sites.google.com/unesp.br/mapeamento-covid19
https://www.cnnbrasil.com.br/saude/2020/06/10/coronavirus-fato-x-ficcao-a-briga-pelo-numero-certo-da-covid-19
https://www.facebook.com/Mapas-do-Brasil-Covid-19-Maps-of-Brazil-106294097779006/
https://www.mixcloud.com/Cultura1077/10062020-cultura-na-mesa/
https://www.youtube.com/watch?v=knBWg-H4wuc

**Comment by endersonmaia** [comment]
[2020-06-09 O Poco - STF manda Ministério da Saúde voltar a divulgar dados acumulados](https://mais.opovo.com.br/jornal/reportagem/2020/06/09/stf-manda-ministerio-da-saude-voltar-a-divulgar-dados-acumulados.html)

para o link acima não encontrei referência ao Brasil.IO

**Comment by endersonmaia** [comment]
no link https://infovis.sei.ba.gov.br/covid19/ não encontrei referencia direta ao Brasil.io

**Comment by turicas** [comment]
Obrigado, @endersonmaia ! O InfoVis da Bahia está usando os dados do Wesley Cota agora (antes estava do Brasil.IO diretamente - o Wesley tem como uma das fontes nossos dados) e a matéria d'O Povo acho que foi uma complementar a uma entrevista que citaram nosso trabalho.
