### ISSUE TITLE
Atualizar clipping

### ISSUE THREAD

**Issue by turicas** [turicas/covid19-br#176]
Coletei mais alguns links (talvez já estejam no clipping), mas ainda não consegui parar para organizar lá (se alguém puder, será de grande ajuda!):

https://apublica.org/2020/06/na-trincheira-contra-o-apagao-de-dados-da-pandemia/
https://brazilian.report/coronavirus-brazil-live-blog/2020/06/07/brazilians-responds-to-government-tampering-with-covid-19-data/
https://brazilian.report/coronavirus-brazil-live-blog/2020/06/14/sao-paulo-mayor-bruno-covas-tested-positive-for-covid-19/
https://www.ocombatente.com/2020/06/08/secretarios-de-saude-do-brasil-lancam-site-para-divulgar-dados-sobre-covid-19/
https://www.tecmundo.com.br/ciencia/152503-respostas-principais-perguntas-covid-19-mapas-graficos.htm
https://www.tecmundo.com.br/ciencia/153965-dados-confiaveis-covid-19-pagina-especial-tecmundo.htm
https://covid.tce.mt.gov.br/extensions/covid/painel-brasil.html
https://neuro.ufrn.br/covid19
https://saude.estadao.com.br/noticias/geral,um-em-cada-tres-casos-de-covid-19-ja-ocorre-fora-das-capitais-e-do-seu-entorno,70003321678

**Comment by endersonmaia** [comment]
resolvido com commit 14bd711

já existiam : 

https://apublica.org/2020/06/na-trincheira-contra-o-apagao-de-dados-da-pandemia/
https://brazilian.report/coronavirus-brazil-live-blog/2020/06/07/brazilians-responds-to-government-tampering-with-covid-19-data/
