### ISSUE TITLE
Corrigir falha no GH Action do goodtables

### ISSUE THREAD

**Issue by endersonmaia** [turicas/covid19-br#177]
A GitHub Action do gootables, está falhando faz tempo, sem ser notado.

O erro deve ser corrigido, e como uma forma de dar mais evidência ao status desta Action, que é agendada para executar uma vez por dia, seria interessante colocar um badge no `README.md`.

https://github.com/turicas/covid19-br/actions?query=workflow%3Agoodtables

**Comment by danielfsbarreto** [comment]
https://github.com/turicas/covid19-br/pull/178
