### ISSUE TITLE
Divergência de dados CE

### ISSUE THREAD

**Issue by jhklarcher** [turicas/covid19-br#186]
Não sei se aqui é o lugar para perguntar sobre isso, mas: estou usando os dados direto do arquivo `caso_full.csv`, percebi que para o Fortaleza os dados não batem com os do painel no https://indicadores.integrasus.saude.ce.gov.br/indicadores/indicadores-coronavirus/coronavirus-ceara, mas vi que a spyder do @endersonmaia pega dados da API lá. Alguém saberia dizer de onde vêm os dados atuais ou o porquê da diferença? Coloquei um exemplo na imagem.

![fortaleza](https://user-images.githubusercontent.com/1714393/85884124-80251200-b7b8-11ea-94aa-da23f5e597f1.jpg)

**Comment by fmplim** [comment]
@jhklarcher pode ser por dois motivos:
- não atualizamos o passado no brasil io; coletamos os dados divulgados a cada dia.
- não usamos a data do resultado do exame (como está no gráfico que vc trouxe), mas a data do dia dos dados coletados.
Espero ter ajudado.
