### ISSUE TITLE
Corrigir script de captura de óbitos registrados em cartório

### ISSUE THREAD

**Issue by turicas** [turicas/covid19-br#189]
Depois da alteração do site do Registro Civil em 12/07, o script de captura `obitos_spider.py` quebrou. Fiz uma atualização ontem corrigindo (05f965aea1fadb0b004973b4732de3563e0da96c), mas ele está baixando dados incompletos. [Veja análise da diferença nos números](https://twitter.com/fabianofpena/status/1283625323586887683?s=19).

Provavelmente teremos que fazer novas requisições, para também capturar os dados de óbitos por causas cardíacas. Se for isso, temos que fazer requisições baixar também para `chart` = `chartCardiac4`.

**Comment by fabianofpena** [comment]
Até o dia 12/07 estava atualizando corretamente.
A coluna "new_deaths_covid19" da tabela obito_cartorio tinha 66080 óbitos computados.

![jul12](https://user-images.githubusercontent.com/44753069/87719391-acb1c580-c789-11ea-9b9d-811e653eb7e6.png)

Na última atualizacao, desapareceram diversos dados, constando apenas 41.353 óbitos.

![atualizado](https://user-images.githubusercontent.com/44753069/87719371-a4f22100-c789-11ea-9217-3832827e1ed0.png)

**Comment by augusto-herrmann** [comment]
Provavelmente está relacionado com esse erro, mas a verificação automática do goodtables também está falhando na checksum para o arquivo `obito_cartorio.csv.gz` após o download:

https://github.com/turicas/covid19-br/runs/892331858?check_suite_focus=true#step:3:910

**Comment by turicas** [comment]
> Provavelmente está relacionado com esse erro, mas a verificação automática do goodtables também está falhando na checksum para o arquivo `obito_cartorio.csv.gz` após o download:
> 
> https://github.com/turicas/covid19-br/runs/892331858?check_suite_focus=true#step:3:910

Opa, não tinha reparado nisso, obrigado! Provavelmente foi quando eu tive que forçar o backup do arquivo (para que o novo, que tem dados incompletos, não entrasse). Já consegui corrigir o script e assim que ele terminar de rodar vou rodar o processo normal de deployment dos dados e esse problema do checksum deve ser corrigido.

**Comment by turicas** [comment]
Script corrigido e dados no ar!

**Comment by augusto-herrmann** [comment]
@turicas, agora está dando [erro de validação](https://github.com/turicas/covid19-br/runs/905005337?check_suite_focus=true).

Você mudou o esquema do csv `obito_cartorio`?

**Comment by fabianofpena** [comment]
> @turicas, agora está dando [erro de validação](https://github.com/turicas/covid19-br/runs/905005337?check_suite_focus=true).
> 
> Você mudou o esquema do csv `obito_cartorio`?

Aqui tá funcionando.
![obitos_cartorio](https://user-images.githubusercontent.com/44753069/88421527-1734b800-cdbf-11ea-96ca-ce4b455c0966.png)

**Comment by augusto-herrmann** [comment]
@fabianofpena estou falando sobre [os testes automatizados do Github](https://github.com/turicas/covid19-br/actions). Siga o link, continua dando erro.
