### ISSUE TITLE
Esse repo contém informações do tipo sanguineo, essas coisas?

### ISSUE THREAD

**Issue by juniorgasparotto** [turicas/covid19-br#214]
Esse repo contém informações do tipo sanguineo, essas coisas?

**Comment by endersonmaia** [comment]
Não

Vc pode consultar a documentação dos campos neste link https://brasil.io/dataset/covid19/caso_full/

Ou aqui https://github.com/turicas/covid19-br/blob/master/api.md

Outras dúvidas comuns em https://github.com/turicas/covid19-br/blob/master/faq.md
