### ISSUE TITLE
ES

### ISSUE THREAD

**Issue by elainecro** [turicas/covid19-br#27]
Boletins:

- [Link para o site dos boletins na Secretaria de Saúde de ES](https://coronavirus.es.gov.br/Noticias)

Status da checagem (anteriores a 20/03):

- [ ] Boletins
- [ ] Casos

Modo e responsável pela conversão:

- Boletins: manualmente por @elainecro
- Casos: manualmente por ?

**Comment by turicas** [comment]
Oi, @elainecro! Obrigado :)
Você poderia enviar email para **turicas *arroba* brasil *ponto* io** com seu nome, sobrenome e WhatsApp? Estamos organizando os voluntários por lá.

**Comment by elainecro** [comment]
Oi @turicas , só vi agora. Acabei de enviar. :)

**Comment by turicas** [comment]
@Bonifacio2  @csmaniottojr @endersonmaia

**Comment by filipesaraiva** [comment]
Oi pessoal, tudo certo? Não sei se esse é o canal certo mas os dados do ES estão atrasados. No momento a última atualização está no dia 27/03.

**Comment by turicas** [comment]
Ainda não está perfeito, mas já fiz uma implementação inicial em `web/spiders/spider_es.py`. Por isso fecharei essa issue.
