### ISSUE TITLE
Dataset temporal dos casos

### ISSUE THREAD

**Issue by mojimi** [turicas/covid19-br#32]
Olá, seria possível disponibilizar no Brasil.io um dataset temporal do casos? Ou seja, cada linha do dataset seria um caso.

Acredito que o dado organizado dessa maneira seja mais versátil.

Entendo que não seria 100% verídico pois nem todo caso tem a data que foi confirmado, mas é a maneira mais próxima de ter uma linha do tempo

**Comment by endersonmaia** [comment]
hoje jé é de certa forma assim, mas com os casos acumulados

bastaria fazer a diferença entre o ATUAL - ANTERIOR, não ?

**Comment by mojimi** [comment]
Verdade, não tinha notado que tinha estava por boletim
