### ISSUE TITLE
Identificador Único

### ISSUE THREAD

**Issue by mojimi** [turicas/covid19-br#37]
Pessoal, não tenho certeza como estão planejando evoluir os dados, mas tem algum plano para um identificador único?

Tentei gerar um a partir da composição da Data+Código IBGE, mas não tenho certeza se é confiável, pois poderia haver dois boletins no mesmo dia certo?

Seria muito util na hora de sincronizar outro banco com os dados desse

**Comment by endersonmaia** [comment]
@mojimi não entendi bem a necessidade de identificador único

caso existam dois boletins no mesmo dia, bastaria repetir, naquela data, os outros boletins

na planilha de dados, bastaria acumular os valores contabilizados

o objetivo de armazenarmos os links pra os boletins e data, é possibilitar a checagem dos dados

**Comment by mojimi** [comment]
@endersonmaia na hora de sincronizar esse dataset com outro, fica dificil saber o que é atualização, no nosso caso não tem a opção de sobrescrever tudo sem downtime pois dependemos de uma API de terceiros...

Caso tivesse algum identificador unico, nem que seja um ID qualquer, poderia usar isso pra verificar

**Comment by endersonmaia** [comment]
não sei como esta sincronização que vc cita funciona, fica difícil propor alguma coisa

sugiro que faça uma proposta de como os dados deveriam estar, quais modificações seriam necessárias na forma como os dados estão disponíveis hoje, ou até a criação de um novo dataset com estes requisitos

quando mais detalhes nos fornecer, melhor

**Comment by mojimi** [comment]
Na tabela casos que está no brasil.io, não tem nada que pode ser usado para identificar unicamente uma linha da tabela.

Então quando tem atualização, e eu preciso saber o que foi atualizado em relação a minha cópia, não tem como saber!

Eu proponho que na própria api do brasil.io seja exportado um id, é usando django não? Django tem o id automático.

Esse id não precisa ter nenhuma lógica, apenas um campo sequencial.

**Comment by turicas** [comment]
@mojimi os dados são muito pequenos, acho que compensa sobrescrever tudo. Nós [disponibilizamos tudo para download por CSV](https://data.brasil.io/dataset/covid19/_meta/list.html) e somando tudo compactado não chega a 30kB. No Brasil.IO para atualizar sempre deletamos a tabela e recriamos.
Se você quer um identificador único para a tabela `caso`, você poderia usar as colunas `date` e `city_ibge_code` para gerar um hash e ter o seu ID. Para boletim poderiam ser `date`, `state` e `url`. No seu processo interno você poderia baixar os CSVs, adicionas as colunas com o ID que você decidiu criar a partir dos valores de outras colunas (como as que citei) e então fazer o processo de atualizar no seu banco local.
