### ISSUE TITLE
Mapa Online utilizando esta API

### ISSUE THREAD

**Issue by endoedgar** [turicas/covid19-br#38]
Acabei de fazer uma prévia de uma interface front end utilizando esta API.

Gostaria de compartilhar com o pessoal.
https://endoedgar.github.io/covid19-monitorbr/

Muito obrigado por disponibilizar esses dados.
A partir do momento que eu tiver limpado o código, irei disponibilizá-lo no meu github. :)

**Comment by endersonmaia** [comment]
Vou adicionar à meta-issue #39 pra gente catalogar estes projetos.
