### ISSUE TITLE
[META] Catalogar referências ao projeto

### ISSUE THREAD

**Issue by endersonmaia** [turicas/covid19-br#39]
Esta issue deve ser usada para compilar lista de projetos, sites, notícias que referenciam o [dataset de COVID-19 do Brasil.IO](https://brasil.io/dataset/covid19/caso) 

Sempre que houver uma referência, basta comentar aqui o link, e serão feitos os ajustes no README.md (ou outro arquivo, caso fique muito extenso).

**Comment by endersonmaia** [comment]
Visualização em mapa https://endoedgar.github.io/covid19-monitorbr/

**Comment by endersonmaia** [comment]
https://www1.folha.uol.com.br/cotidiano/2020/03/brasil-tem-ao-menos-172-cidades-com-casos-confirmados-de-coronavirus.shtml

**Comment by augusto-herrmann** [comment]
> Visualização em mapa https://endoedgar.github.io/covid19-monitorbr/

Muito bom! Seria ótimo colocar um link para essa visualização no próprio site do Brasil.io, para que mais pessoas possam ficar sabendo.

**Comment by filipesaraiva** [comment]
Fiz uma página para apresentar gráficos com dados de casos confirmados e mortos por estado e pro Brasil inteiro utilizando a API de vocês. Está na minha página pessoal, mas depois farei algumas modificações e colocarei em algum site dos meus laboratórios da UFPA. [COVID-19 :: Dashboard](https://filipesaraiva.info/corona-grafico.html).

**Comment by dhonysilva** [comment]
https://colab.research.google.com/drive/1zhDMIEY1M_QZdoJdGis9p0GMJ2K2pDSk

Estou escrevendo esse Notebook. O propósito com esse documento é apresentar a didática de Análise Exploratória de dados, para quem está interessado em aprender Jupyter Notebook, Pandas e libs de visualização como a Matplotlib e Ploty.

**Comment by dhonysilva** [comment]
https://umsaldanha.com/grafana/d/vdxF8frZz/covid19-brazil?orgId=1&kiosk

Os gráficos do Brasil utilizam os dados da Brasil.IO.

Dashboard desenvolvido em Grafana.

**Comment by endersonmaia** [comment]
Agora as referência são catalogadas no arquivo [clipping.md](https://github.com/turicas/covid19-br/blob/master/clipping.md)

**Comment by endersonmaia** [comment]
fechando esta issue

no commit 511698b foi adicionado o arquivo `clipping.md` ao CODEOWNERS, e assim será sempre solicitada a minha revisão, e assim dá pra rastrear melhor os PR de atualização ao clipping
