### ISSUE TITLE
Melhorar documentação da API e acesso aos dados

### ISSUE THREAD

**Issue by endersonmaia** [turicas/covid19-br#41]
Para facilitar o uso dos dados que estão sendo gerados, precisamos melhora a documentação de como fazer uso destes dados, seja [via API](https://brasil.io/api/dataset/covid19/caso/data) ou seja buscando os [arquivos](https://data.brasil.io/dataset/covid19/caso.csv.gz).

**Comment by turicas** [comment]
Fiz um texto/resumo aqui: https://github.com/endoedgar/covid19-monitorbr/issues/1

**Comment by endersonmaia** [comment]
acho que poderíamos adicionar uns exemplos com `curl`

- [ ] adicionar exemplos com curl

**Comment by turicas** [comment]
Não comentei aqui, mas subi o arquivo [api.md](https://github.com/turicas/covid19-br/tree/master/api.md) que estou enviando para todo mundo que me manda dúvidas sobre a utilização da API.

**Comment by saramortara** [comment]
olá pessoal. primeiro, parabéns pela iniciativa, precisamos de dados realmente abertos. Escrevo aqui pois estou com uma dúvida em relação a API. A gente fez um pacote de R ([coronabr](https://liibre.github.io/coronabr/)) para baixar os dados diretamente da API. No início apenas o endereço https://brasil.io/api/dataset/covid19/caso/data retornava os dados completos, mas agora precisamos também de https://brasil.io/api/dataset/covid19/caso/data?page=2. É isso mesmo?

**Comment by turicas** [comment]
@saramortara sim, a API retorna 10k registros por página e você precisa paginar. Para facilitar você pode [baixar o CSV compactado](https://github.com/turicas/covid19-br/blob/master/api.md#acesso-aos-dados).

**Comment by dhonysilva** [comment]
Só uma dúvida básica (e talvez isso ajude na documentação). Os na API são acumulados ou absolutos de cada dia?

**Comment by turicas** [comment]
@dhonysilva acumulados.

**Comment by dhonysilva** [comment]
Estamos falando em 10.000 registros por página mas na verdade são 1000.

**Comment by dhonysilva** [comment]
Não sei se esse é o tópico correto.

O campo confirmed é do tipo `int64` e o deaths `float64`. Não sei realmente deve ser assim mas isso causa alguns problemas em ferramentas de análises.

**Comment by turicas** [comment]
> Não sei se esse é o tópico correto.
> 
> O campo confirmed é do tipo `int64` e o deaths `float64`. Não sei realmente deve ser assim mas isso causa alguns problemas em ferramentas de análises.

Você está enganado. Veja `fields`em: https://brasil.io/api/dataset/covid19

**Comment by endersonmaia** [comment]
> Não sei se esse é o tópico correto.
> 
> O campo confirmed é do tipo `int64` e o deaths `float64`. Não sei realmente deve ser assim mas isso causa alguns problemas em ferramentas de análises.

no JSON é só `number`, quem define o tipo estrito é a linguagem que faz o parsing e processa os dados
