### ISSUE TITLE
Link direto para download dos dados

### ISSUE THREAD

**Issue by Smolski** [turicas/covid19-br#46]
Olá! Parabéns pelo trabalho de agrupar as informações municipais e estaduais sobre o covid! Tem algum link para que eu possa importar diretamente no RStudio os dados?

**Comment by endersonmaia** [comment]
Na seção [Dados ](https://github.com/turicas/covid19-br#dados) do README.md tem o [link para o dataset completo](https://data.brasil.io/dataset/covid19/_meta/list.html)

Me avisa se serviu

**Comment by Smolski** [comment]
Deu certo! Vi que não tem os dados do Rio Grande do Sul.

**Comment by Smolski** [comment]
Aqui no RS as páginas com os dados:

https://saude-admin.rs.gov.br/upload/arquivos/202003/25182055-informe-epidemiologico-rs-2019-ncov-25-03-2020.pdf

http://ti.saude.rs.gov.br/covid19/

**Comment by endersonmaia** [comment]
> Deu certo! Vi que não tem os dados do Rio Grande do Sul.

Fechando issue
