### ISSUE TITLE
Monitorar novos boletins

### ISSUE THREAD

**Issue by biketrooper** [turicas/covid19-br#47]
Montei um PHP+cron que verifica se as páginas de boletins tem alteração e avisa por e-mail.
Código (sou designer!): https://gist.github.com/biketrooper/220e4f091296a68aba3692664b968952

Vou testar em outros estados (ainda tem muitos falsos positivos) e gerar um feed RSS/XML que pode acionar leitores e/ou um bot no rocket.chat

**Comment by biketrooper** [comment]
@turicas > No fim é um
`wget -O $URL | sha1sum -c $url_sha1sum`

**Comment by endersonmaia** [comment]
@biketrooper eu sugiro fechar um ciclo primeiro, e depois evoluir os estados

pega o estado que vc acha que tá mais estável, sem muito falso positivo, e faz o esquema de cron, e fecha com a comunicação com o BOT pro rocket.chat

esse RSS deixaria para um segundo momento, como os voluntários todos estão todos no rocket.chat, acho mais efetivo testarmos algo direto com o bot

**Comment by endersonmaia** [comment]
para aproveitarmos a infra do Brasil.IO, ideal é fazer em bash ou python, como o @turicas comentou

eu criei um Grupo Privado, que podemos testar o Bot, vou adicionar vc lá

e pedir pro @turicas adicionar o bot e vamos testando

**Comment by turicas** [comment]
Implementando aqui: https://github.com/turicas/covid19-br/tree/feature/bot-notify-page-changes

**Comment by endersonmaia** [comment]
implementado no PR #48
