### ISSUE TITLE
AL e CE sumiram das opções do site

### ISSUE THREAD

**Issue by hitalos** [turicas/covid19-br#50]
Na url https://brasil.io/dataset/covid19/caso não aparece mais as opções AL e CE no filtro de UF.

![image](https://user-images.githubusercontent.com/1332910/77812232-bdc1b400-707e-11ea-8126-c36b0efb1f01.png)

**Comment by turicas** [comment]
Foi um erro no deployment, já estão de volta.

**Comment by turicas** [comment]
@hitalos desculpe usar esse espaço pra isso, mas não encontrei seu contato em outros lugares: parabéns pelo mapa que você criou! Ficou bem legal. O código é software livre? Gostaríamos de colocar uma visualização no próprio Brasil.IO e não estamos com muito tempo para desenvolver.

**Comment by hitalos** [comment]
Opa @turicas ! Desculpe pela demora. Dei um acabamento aqui nos scripts e publiquei aqui:
https://github.com/hitalos/covid19

Conte comigo se precisarem de ajuda.

**Comment by hitalos** [comment]
Agora foi o RS que deu uma sumida.

**Comment by turicas** [comment]
@hitalos já dectectamos e voltou. Estamos alterando o script que consolida os dados para que isso não aconteça mais.
