### ISSUE TITLE
Colocar horário reportado pelo robô em UTC-3

### ISSUE THREAD

**Issue by turicas** [turicas/covid19-br#53]
Atualmente ele está reportando em UTC. Acredito que seja só trocar a função [`last_check_str`](https://github.com/turicas/covid19-br/blob/master/bot/check_urls.py#L18).

**Comment by lunhg** [comment]
Tlvz pytz?

    import` datetime
    import pytz
    tz = pytz.timezone('America/Sao_Paulo')
    ct = datetime.datetime.now(tz=tz)
    ct.isoformat()

**Comment by lunhg** [comment]
Creio que modificando a linha 80 já dá:

        url_info["last_check_datetime"] = datetime.datetime.now()

para:

        tz = pytz.timezone('America/Sao_Paulo')
        url_info["last_check_datetime"] = datetime.datetime.now(tz=tz)
