### ISSUE TITLE
Falta de repetição nos dados

### ISSUE THREAD

**Issue by raphageoc** [turicas/covid19-br#56]
Estou trabalhando em um web mapa  para representação espaço-temporal dos dados, porém percebi a diminuição de dados do dia 27/03/2020 para o dia 28/03/2020. Filtrando os dados por dia, no dia 27/03 retorna 311 registros e no dia 28/03 retorna 270, deveria aumentar, certo?
Fiz o download  do csv com todos os dados e notei que para cidade de Iracemápolis há dados até dia 27/03. Os dados deveriam repetir mesmo que não tivesse atualizações?
--

**Comment by endersonmaia** [comment]
@raphageoc dá uma lida no [CONTRIBUTING.md](https://github.com/turicas/covid19-br/blob/master/CONTRIBUTING.md)

Lá tem um link pra [Metodologia](https://docs.google.com/document/d/1escumcbjS8inzAKvuXOQocMcQ8ZCqbyHU5X5hFrPpn4/edit?usp=sharing).

Algumas dúvidas são respondidas lá, inclusive o motivo de poder ter alguns dados que podem mudar de um dia para o outro.
