### ISSUE TITLE
Citacao em artigo científico.

### ISSUE THREAD

**Issue by lsbastos** [turicas/covid19-br#62]
Olá,

Estou usando o dado de vocês e do Wesley Cota em um manuscrito e gostaria de cita-los adequadamente no artigo. Vocês tem um .bib?  O Wesley me passou um doi para o kaggle, talvez o dados de vcs já esteja por lá eu nao encontrei.

O dele:  https://doi.org/10.34740/KAGGLE/DSV/1042812

Se vcs tiverem um tb seria ótimo.

Obrigado

**Comment by dhonysilva** [comment]
@turicas talvez fosse interessante criar um user da brasil.io no kaggle.

**Comment by turicas** [comment]
@lsbastos, no momento não temos cadastro no DOI - você saberia me informar como funciona o processo?

@dhonysilva não disponibilizamos os dados no Kaggle por conta dos limites impostos (vários dos datasets do Brasil.IO possuem às vezes dezenas de GBs).

**Comment by lsbastos** [comment]
Obrigado,

Acho que pro artigo que to escrevendo posso colocar um link pro site resolve. 

Qdo precisei pendurei um banco no [zenodo](https://zenodo.org/), mas vcs tem muitas bases. Aí realmente nao sei.

**Comment by turicas** [comment]
Pessoal, não tive tempo de ver como seria feita essa citação e já fizeram diversas citações, então reuni [na seção Licença e Citação do README](https://github.com/turicas/covid19-br/blob/master/README.md#licen%C3%A7a-e-cita%C3%A7%C3%A3o) informações sobre isso e também coloquei um link para isso na FAQ.
