### ISSUE TITLE
Dados I Metadados - visualização

### ISSUE THREAD

**Issue by tatianasb** [turicas/covid19-br#64]
Atualmente, dá a entender que o DADOS é referente à coluna de busca da esquerda e METADADOS é referente à coluna de busca da direita. Não é visualmente lógico que são duas tabs diferentes e não dá a entender que são clicáveis.

**Comment by tatianasb** [comment]
Como aparece atualmente:
![2020-04-01 10 54 09](https://user-images.githubusercontent.com/19399276/78118746-b9432580-7407-11ea-9e82-60f5657ab449.jpg)

**Comment by tatianasb** [comment]
Uma solução seria:
![brasilio - covid - tela 1](https://user-images.githubusercontent.com/19399276/78120601-88182480-740a-11ea-9140-94a86ea9e054.png)

**Comment by turicas** [comment]
Movida pra: https://github.com/turicas/brasil.io/issues/197
