### ISSUE TITLE
remover menções a all feitas pelo bot

### ISSUE THREAD

**Issue by Bonifacio2** [turicas/covid19-br#67]
Sempre que o nosso bot manda mensagens ele começa com "@all", o que dispara uma notificação pra todo mundo no canal. Como agora tempos voluntários por estados e o monitoramento do bot também é por estado, acho que podemos reduzir as notificações fazendo esse ajuste fino para que o bot mencione apenas as pessoas que estão monitorando um determinado estado específico. O que acham?

**Comment by endersonmaia** [comment]
Na planilha [Brasil.IO - COVID19 - Links por UF](https://docs.google.com/spreadsheets/d/1S77CvorwQripFZjlWTOZeBhK42rh3u57aRL1XZGhSdI/edit#gid=0) , cada linha representa um Estado e tem as colunas `canal` e `voluntarios`

em `voluntários` tem os nomes dos usuários do chat.brasil.io responsáveis por aquele Estado, separados por vírgula
