### ISSUE TITLE
Reunir mortes por pneumonia e insuficiência respiratória

### ISSUE THREAD

**Issue by ribeirojose** [turicas/covid19-br#75]
Pneumonia e insuficiência respiratória e pneumonias não requerem notificação compulsória imediata. Dado o pressuposto de que não estávamos/estamos dando conta de fazer testes pra detecção do vírus, esse dado pode nos ajudar a acompanhar a evolução da letalidade desde antes de começarmos a testar para o vírus (se tivermos dados de controle dos outros anos).

**Comment by turicas** [comment]
@ribeirojose você tem ideia de onde existem dados oficiais sobre isso, que estejam atualizados?

**Comment by ribeirojose** [comment]
Infelizmente nenhum dado atualizado público que sirva como uma fonte estável de informação.  Estava falando com pessoal envolvido no laboratório Bridge (que monta solucões pro sus, tipo o datasus), e não sei nem se seria possível abrir alguma api pra acesso desses dados. Talvez algum projeto conseguisse negociar acesso a esses dados através do município, mas não tenho certeza de como começar a fazer isso.

**Comment by turicas** [comment]
Adicionei os dados dos cartórios: https://blog.brasil.io/2020/04/10/obitos-por-covid19-no-brasil-sao-maiores-que-os-divulgados-oficialmente-passamos-de-mil-mortes-no-dia-6-de-abril/
