### ISSUE TITLE
PE

### ISSUE THREAD

**Issue by turicas** [turicas/covid19-br#8]
Boletins:

- [Link para o site dos boletins na Secretaria de Saúde de PE](http://www.pe.gov.br/blog/saude/)

Status da checagem (anteriores a 20/03):

- [ ] Boletins
- [ ] Casos

Modo e responsável pela conversão:

- Boletins: manualmente por ?
- Casos: manualmente por ?

**Comment by endersonmaia** [comment]
neste link, https://www.cievspe.com/novo-coronavirus-2019-ncov, os boletins parecem estar mais organizados

o único boletim é do dia [19/03/2020](https://12ad4c92-89c7-4218-9e11-0ee136fa4b92.filesusr.com/ugd/3293a8_52601cf563cb449e97caeeb588ae3cb6.pdf), segue trecho com números

![Captura de Tela 2020-03-20 às 23 46 33](https://user-images.githubusercontent.com/370/77217939-1afcb900-6b05-11ea-8a69-cbb70825fd55.png)

```
2020-03-19;https://12ad4c92-89c7-4218-9e11-0ee136fa4b92.filesusr.com/ugd/3293a8_52601cf563cb449e97caeeb588ae3cb6.pdf
```

**Comment by endersonmaia** [comment]
na página 4 do PDF tem os dados por Município

![Captura de Tela 2020-03-20 às 23 54 17](https://user-images.githubusercontent.com/370/77218056-2b616380-6b06-11ea-911e-10711548cbf1.png)

**Comment by leuthier** [comment]
Por aqui é constantemente atualizado com informações da secretaria de saúde do estado:
https://www.irrd.org/covid-19/#pernambuco

**Comment by endersonmaia** [comment]
@leuthier massa, e aqui https://www.irrd.org/covid-19/#brazil tem até um link pra um CSV por Município e UF do Brasil todo, mas não tenho as manhas de conseguir baixar isso aí

@turicas dá uma olhada

**Comment by turicas** [comment]
Pessoal, obrigado pelos links! Fiz uma apuração e o https://www.cievspe.com/novo-coronavirus-2019-ncov parece ser da secretaria de saúde estadual de PE, então vamos usar esse como referência para pegar os boletins.
Sobre o irrd: não consegui checar se é oficial, então nesse caso prefiro ir nos boletins que estão no CIEVS PE.

**Comment by turicas** [comment]
Opa, voltando atrás com relação ao CIEVS: tem um link mais confiável, que tem mais boletins: http://www.pe.gov.br/blog/saude/

@endersonmaia @leuthier preciso de ajuda: vocês conseguem acessar [essa planilha](https://docs.google.com/spreadsheets/d/11dZ0Ikcpnq2mBCP_B4ltOfM1OIvuuP_WLwGtHih4lXI/edit?usp=sharing) e checar se existe algum outro boletim que não está ali? Lembrando que uma notícia que, de alguma forma, mostra mudança no número de casos (seja suspeitos ou confirmados) pode ser configurar como boletim (daí precisaremos fazer as contas para atualizar os dados), ou seja, não precisa ser um boletim "convencional", basta ter a informação que precisamos.

**Comment by bplmp** [comment]
Não sei se já viram http://dados.seplag.pe.gov.br/

**Comment by plguedes** [comment]
Opa, corrigindo: http://dados.seplag.pe.gov.br/apps/corona.html#painel

**Comment by turicas** [comment]
Alguém se voluntaria a [seguir esses passos](https://github.com/turicas/covid19-br#criando-scrapers) e criar um PR com o scraper?

**Comment by AleDTS** [comment]
Olá pessoal. 

@turicas o scraper seria para este link http://dados.seplag.pe.gov.br/apps/corona.html mesmo certo? Não encontrei um link direto para pegar o csv da [tabela Dados PE](http://dados.seplag.pe.gov.br/apps/corona.html#dados-pe), porém ele traz os mesmos dados num json dentro do html e dá para parsear.

**Comment by turicas** [comment]
> Olá pessoal.
> 
> @turicas o scraper seria para este link http://dados.seplag.pe.gov.br/apps/corona.html mesmo certo? Não encontrei um link direto para pegar o csv da [tabela Dados PE](http://dados.seplag.pe.gov.br/apps/corona.html#dados-pe), porém ele traz os mesmos dados num json dentro do html e dá para parsear.

Sim. E para facilitar, mudei um pouco as regras de criação de scraper: você pode fazer o scraper devolver uma lista de dicionários com as seguintes chaves: `state`, `date`, `city`, `confirmed` e `deaths`. Seria um dicionário para cada município, mais 2: 1 com city = "Importados/Indefinidos" e 1 com city = "TOTAL NO ESTADO".

**Comment by turicas** [comment]
Ainda não está perfeito, mas já fiz uma implementação inicial em `web/spiders/spider_pe.py` dos dados da SEPLAG. Por isso fecharei essa issue.
