### ISSUE TITLE
Última versão do dataset completo

### ISSUE THREAD

**Issue by zargo** [turicas/covid19-br#81]
Olá! Eu acho que atualizaram a última versão do arquivo caso-full.csv.gz incorretamente. O arquivo anterior tinha mais de 3 MB e a última versão apenas 173.18kB. O formato foi alterado ou realmente o arquivo está errado?

**Comment by zargo** [comment]
Na verdade, esse dataset está diferente. Não apresenta mais "place_type" == state e só apresenta os dados de cada município a partir do primeiro caso.

**Comment by turicas** [comment]
@zargo essa tabela ainda está em construção e não foi publicada oficialmente - o arquivo está sendo enviado para testes, mas perceba que a tabela caso_full ainda não existe no dataset no Brasil.IO.
Estou trabalhando no branch feature/caso-full e só quando eu terminar, fizer o merge e publicar a tabela no Brasil.IO é que consigo te dar garantias sobre a estabilidade dos dados nela.
