### ISSUE TITLE
erro na descrição da variável "deaths_covid19"

### ISSUE THREAD

**Issue by avila** [turicas/covid19-br#82]
Creio que haja um erro na descrição da variável "deaths_covid19" [aqui nas descrições das tabelas](https://github.com/turicas/covid19-br/blob/master/api.md#%C3%B3bitos-registrados-em-cart%C3%B3rio), onde diz: 

- deaths_covid19: quantidade de óbitos em decorrência de suspeita ou confirmação de covid19 registrados nesse dia e mês (de date) para o estado em state, porém para o ano de 2019.

essa variável é para o ano de 2020, certo? 
(também me confundi, por causa do dígito 19 ao final. Se não for muito complicado, talvez fosse melhor deixar apenas covid mesmo.)

**Comment by turicas** [comment]
Não tinha visto essa issue, mas corrigi o erro há 8 dias atrás em 3 commits: 77e7b2128bf1baff3aa1c93b086bdcdda295fc7d 3028bbfc4a621e85cdbe32a2c4b07ec164621b61 e aed3ce82fe238a3a77c04bd83be4af5a1a90e429.
