### ISSUE TITLE
Dados Históricos de Municípios de São Paulo - Regiões Administrativas DR's

### ISSUE THREAD

**Issue by gasilva** [turicas/covid19-br#87]
Olá,

Tudo bem? O problema que estes dados de cidade são somente o do dia atual. Tenho que ter o histórico! Você tem um scrapper para isso? o formato da URL é http://www.seade.gov.br/wp-content/uploads/2020/04/Dados-covid-19-municipios.csv portanto os dados históricos são acessíveis em diferentes URL's. É possível tem um arquivo CSV, feito o download automático, com todas as cidades/DR's em colunas, as linhas como datas e o número de casos? e outra com a mesma estrutura para os mortos?

Desenvolvi um modelo SEAIR-D para a previsão e estou trabalhando com o grupo do IPT nesse assunto mas faltam dados atualizados para a gente.

Colabore e watch em:
https://github.com/gasilva/dataAndModelsCovid19

Um abraço
Guilherme

**Comment by turicas** [comment]
@gasilva acho que você não entendeu o propósito desse projeto. Por isso, estou fechando a issue.
Caso queira saber mais, leia as últimas publicações em [blog.brasil.io](https://blog.brasil.io/).
