### ISSUE TITLE
Incluir esquema de CSV nas recomendações às Secretarias de Saúde

### ISSUE THREAD

**Issue by augusto-herrmann** [turicas/covid19-br#89]
Dentre as [recomendações às Secretarias de Estado de Saúde](https://github.com/turicas/covid19-br/blob/master/recomendacoes.md) já existe um modelo de mensagem para enviar ao entrar em contato.

Acho que seria importante também recomendar um modelo de planilha. Se todas as SES usassem CSVs no mesmo modelo, facilitaria ainda mais coletar os dados. Se conseguirmos convencê-los a fazer em CSV também, não custa sugerir de uma vez o esquema da planilha também.

**Comment by turicas** [comment]
Sim. O ideal seria pensarmos num modelo que tenha mais dados do que estamos coletando agora (ideal), adicionando suspeitos, recuperados etc.
Além da tabela de casos com valores totalizados, talvez outras tabelas, como faixa etária dos infectados, perfil dos óbitos etc.

**Comment by jessfranca** [comment]
Não seria o caso de fazer um modelo simples que eles consigam fazer prontamente?
E deixar quem sabe duas sugestões: factível e ideal?
Acho que optando pelo mais simples a chance de aderência das secretarias seria maior.

**Comment by turicas** [comment]
> Não seria o caso de fazer um modelo simples que eles consigam fazer prontamente?
> E deixar quem sabe duas sugestões: factível e ideal?
> Acho que optando pelo mais simples a chance de aderência das secretarias seria maior.

@jessfranca, acho que isso pode complicar e atrapalhar no processo de extração. Nesse sentido, é melhor definirmos colunas obrigatórias e opcionais.

**Comment by bjverde** [comment]
Meus dois centavos,

Considerando o problema #86  - dados atualizados retroativamente. Acredito que uma das colunas deveria ser a data da atualização do dados.

**Comment by augusto-herrmann** [comment]
Esta tabela, do boletim da SES/DF, é interessante por mostrar, por faixa etária, os casos confirmados, hospitalizados (divididos entre enfermaria e UTI) e óbitos.

![Captura de tela de 2020-04-16 17-34-56](https://user-images.githubusercontent.com/1058414/79504161-c7e52b80-8008-11ea-8666-f5e72c789917.png)

Faltam aí, é claro, os casos recuperados.

Entretanto, quando acrescentamos a temporalidade (dias anteriores), a forma de organizar os dados fica mais complexa. O que acham que deveríamos recomendar? Uma tabela para cada dia? E quando fossem revisados retroativamente (vide #86), atualizaria as tabelas dos dias anteriores também?

**Comment by georgevbsantiago** [comment]
Olá, pessoal.
Vi a discussão agora e não tive tempo de ler tudo, mas deixo uma observação:
Essas recomendações estão considerando o sistema que está coletando os dados, no caso o : eSUS VE ?

Seguem algumas informações:
- O Sistema foi lançado no final de março para notificar os casos de COVID-19.
- Site: https://datasus.saude.gov.br/esusve/
- Manual: https://datasus.saude.gov.br/wp-content/uploads/2020/04/Tutorial-%E2%80%93-e-SUS-VE-1.0a-31-03-2020.pdf
- email da equipe de desenvolvimento: esusve.suporte@saude.gov.br

**Comment by augusto-herrmann** [comment]
@georgevbsantiago, obrigado pelas informações. O Brasil.io usa como fonte de dados as Secretarias de Estado de Saúde diretamente, e não o Ministério da Saúde. Se a sua ideia é incluir o Ministério da Saúde como uma nova fonte de dados, sugiro abrir uma nova *issue* em separado sobre isso, ou sugerir lá no [chat do Brasil.io](https://chat.brasil.io/).

**Comment by augusto-herrmann** [comment]
Encontrei um esquema de CSV para as contagens da Covid-19 [aqui](https://github.com/ISA-tools/frictionless-collab/blob/master/covid19-case-counts/covid-19-case-tally-report-table.json) (*Covid-19 case tally report*). Pelo que vi, parece que é [baseado em um modelo do CDC dos Estados Unidos](https://discuss.okfn.org/t/towards-a-data-schema-for-covid-19-epidemiological-and-response-data/9353/4?u=herrmann).

**Comment by turicas** [comment]
Algumas informações úteis:

- [Reportagem sobre número de testes/falta de padronização](https://twitter.com/Cambricoli/status/1254772660845699073)
- O grupo [Análise Covid19](https://analisecovid19.wordpress.com/) me sugeriu coletar os seguintes dados: casos confirmados (já coletamos), óbitos (já coletamos), casos críticos, casos recuperados, casos suspeitos e casos testados. Não ficou clara a sugestão metodológica para esses, exemplo: um caso suspeito pode entrar como testado também? Como poderíamos somar o total de casos (para não "contar mais de uma vez" uma pessoa que, porventura, possa estar em mais de um grupo)?

**Comment by endersonmaia** [comment]
> Algumas informações úteis:
> 
> * [Reportagem sobre número de testes/falta de padronização](https://twitter.com/Cambricoli/status/1254772660845699073)
> * O grupo [Análise Covid19](https://analisecovid19.wordpress.com/) me sugeriu coletar os seguintes dados: casos confirmados (já coletamos), óbitos (já coletamos), casos críticos, casos recuperados, casos suspeitos e casos testados. Não ficou clara a sugestão metodológica para esses, exemplo: um caso suspeito pode entrar como testado também? Como poderíamos somar o total de casos (para não "contar mais de uma vez" uma pessoa que, porventura, possa estar em mais de um grupo)?

só reforçando, usando Alagoas como referencia, as informações além de `confirmados` e `obitos` não são detalhadas por município

![Captura de Tela 2020-04-27 às 12 16 58](https://user-images.githubusercontent.com/370/80389062-025c8d00-8881-11ea-894a-e52a3b8ff0bc.png)

Fonte: http://www.saude.al.gov.br/wp-content/uploads/2020/04/ERRATA-Informe-COVID-19-nº-51-26-DE-ABRIL-16h57.pdf

**Comment by endersonmaia** [comment]
complementando meu comentário, deveríamos sugerir que estes dados de `suspeitos`, `descartados`, `testados` e agins,  tenham o mesmo nível de detalhe por município , ou propor como opcional, e ao menos tenha a posição **No Estado / Dia**

**Comment by turicas** [comment]
@endersonmaia concordo!

Outro link com informações relevantes para esse trabalho: https://drive.google.com/file/d/1wLoB84KacF-uVALKAKmzq7fyltXzIXay/view

**Comment by endersonmaia** [comment]
Encontrei isso aqui no schema.org, pode ter serventia para definição dos campos num "padrão" que parecer ser bastante adotado, me refiro ao `schema.org`.

http://blog.schema.org/2020/03/schema-for-coronavirus-special.html

**Comment by endersonmaia** [comment]
http://ok.org.br publicou esse template aqui : https://docs.google.com/spreadsheets/d/1mgZe2GjKz_7zH5w4cEVfTh4LfvqDlUs3lxFSD6NJFjw/edit#gid=1132363805

Ver: https://transparenciacovid19.ok.org.br/files/Toolkit_1_microdados_basicos.pdf

**Comment by turicas** [comment]
> http://ok.org.br publicou esse template aqui : https://docs.google.com/spreadsheets/d/1mgZe2GjKz_7zH5w4cEVfTh4LfvqDlUs3lxFSD6NJFjw/edit#gid=1132363805
> 
> Ver: https://transparenciacovid19.ok.org.br/files/Toolkit_1_microdados_basicos.pdf

Consegue incluir essas sugestões nas recomendações?

**Comment by endersonmaia** [comment]
vou assumir a issue, pretendo fazer isso amanhã

**Comment by augusto-herrmann** [comment]
> http://ok.org.br publicou esse template aqui : https://docs.google.com/spreadsheets/d/1mgZe2GjKz_7zH5w4cEVfTh4LfvqDlUs3lxFSD6NJFjw/edit#gid=1132363805

Bem que a @campagnucci me disse que a OKBR iria abrir uma consulta para um padrão de dados. Já convidei o pessoal de lá a interagir aqui também.

Mas essa é uma proposta de padrão de dados para os microdados. Acho que seria útil ter também, e essa é a proposta original dessa *issue*, ter um padrão de dados para as contagens agregadas. Até porque é possível ter algum dado que não possa ser divulgado individualmente para preservar a intimidade das pessoas, mas na forma agregada possa ser divulgado.

Então estamos falando de dois padrões de dados: um para contagens ("*tally*") com dados agregados e outro para microdados.

**Comment by augusto-herrmann** [comment]
Só para registrar, há também um PL tramitando na Câmara dos Deputados sobre a padronização de dados sobre pandemia:

[Projeto prevê transparência e parâmetros mínimos para dados sobre pandemia](https://www.camara.leg.br/noticias/658327-projeto-preve-transparencia-e-parametros-minimos-para-dados-sobre-pandemia/)

**Comment by endersonmaia** [comment]
> ...Até porque é possível ter algum dado que não possa ser divulgado individualmente para preservar a intimidade das pessoas, mas na forma agregada possa ser divulgado.

Neste modelo da OKBR, não percebi nenhum dado que possa identificar individualmente uma pessoa.

Pensei que atualizar o arquivo `recomendacoes.md` sugerindo o modelo proposto pela OKBR, e fazendo referência ao documento e planilha deles.

Se as SES divulgarem nesse formato proposto, o Brasil.IO pode escolher quais dados compilar ou não.

O que acham ?

/cc @turicas @augusto-herrmann

**Comment by turicas** [comment]
Acabei de atualizar [as nossas recomendações](https://github.com/turicas/covid19-br/blob/master/recomendacoes.md) com um modelo de dados agrupados e citando o modelo de microdados da OK. Alguém poderia adicionar exemplos, por favor? Poderiam ter exemplos de dois estados: PR, por exemplo, libera os importados por município, já outros liberam somente o total.

**Comment by endersonmaia** [comment]
> Acabei de atualizar [as nossas recomendações](https://github.com/turicas/covid19-br/blob/master/recomendacoes.md) com um modelo de dados agrupados e citando o modelo de microdados da OK. Alguém poderia adicionar exemplos, por favor? Poderiam ter exemplos de dois estados: PR, por exemplo, libera os importados por município, já outros liberam somente o total.

mandei no PR #125
