### ISSUE TITLE
RR

### ISSUE THREAD

**Issue by whaner** [turicas/covid19-br#91]
Boletins:

-  [Link para o site dos boletins na Secretaria de Saúde de RR](https://www.saude.rr.gov.br/index.php/informacoesx/coronavirus/informacoes-coronavirus)

Status da checagem (anteriores a 20/03):

- [X] Boletins
- [X] Casos

Modo e responsável pela conversão:

- Boletins: manualmente por @whaner e @itevaldojr
- Casos: manualmente por ?

**Comment by turicas** [comment]
https://roraimacontraocorona.rr.gov.br/winner/public/mapa.xhtml

**Comment by turicas** [comment]
Ainda não está perfeito, mas já fiz uma implementação inicial em `web/spiders/spider_rr.py`. Por isso fecharei essa issue.
